### ISSUE TITLE
Core foundation unexpectedly returned null string

### ISSUE THREAD

**Issue by TENX-S** [RustAudio/rodio#298] opened 2020-07-08 15:37 UTC
Here's my code(just followed the [doc](https://docs.rs/rodio/0.11.0/rodio/) ):

```
use std::fs::File;
use std::io::BufReader;
use rodio::Source;

fn main() {

    let device = rodio::default_output_device().unwrap();
    let file = File::open("/Users/xxx/Music/MyMusic/xxxx - xxxx.flac").unwrap();
    let source = rodio::Decoder::new(BufReader::new(file)).unwrap();
    rodio::play_raw(&device, source.convert_samples());
}
```

Error message:

thread 'main' panicked at 'No device name: BackendSpecific { err: BackendSpecificError { description: "core foundation unexpectedly returned null string" } }', /Users/xxx/.cargo/registry/src/rodio-0.11.0/src/engine.rs:113:32

**Comment by OvermindDL1** [comment] 2020-07-08 15:51
I thought the core foundation required all devices to have a string name, if some driver is returning null then that sounds like a broken driver...  What are all audio devices that you have in your system?  And which one has an empty "name" entry?

**Comment by est31** [comment] 2020-07-08 16:11
This is a cpal bug, dupe of https://github.com/RustAudio/cpal/issues/398 and should be fixed by https://github.com/RustAudio/cpal/pull/399

**Closed by est31** 2020-07-08 16:11 UTC
