### ISSUE TITLE
skip_duration not instant

### ISSUE THREAD

**Issue by janwirth** [RustAudio/rodio#392] opened 2021-08-22 19:19 UTC
I was wondering how to build a scrubbable progress bar with rodio - `Source.skip_duration` is not instant, so this method won't work. If rodio is not the right tool to build an audio player, can you please point me in the right direction?

**Comment by VanillaBrooks** [comment] 2021-11-11 21:58
related to #176 and #338 (with hacky workaround)

As far as I have seen `rodio` is the simplest way to do this in rust. If low latency is really important on the audio you may be better off building in another language, or working on backend support.

**Comment by woelper** [comment] 2021-11-21 19:58
I don't know if that helps, but I've built a [very simple audio player](https://github.com/woelper/lynx) with [seeking](https://github.com/woelper/lynx/blob/417385111523ee05ab211187cf2036f96fc37ac2/src/app.rs#L158). It's using Kira as an audio lib and seeking was easy to do. The downside is that kira does not stream (yet), so loading audio takes longer than in `rodio`. Seeking is instant though.

**Comment by est31** [comment] 2021-11-22 10:50
Closing as dupe of #176

**Closed by est31** 2021-11-22 10:50 UTC

**Comment by est31** [comment] 2021-11-22 11:14
That being said, it's not a *perfect* dupe of #176, as one can think of fast-mode `skip_duration` like functionality in many formats, which is basically linear seeking, and easier to implement than logarithmic seeking. E.g. in vorbis it's easy to find out the number of samples in a packet without decoding it, so it is possible to skip the given number of samples if needed.
