### ISSUE TITLE
Allow to disable cpal playback

### ISSUE THREAD

**Issue by qarmin** [RustAudio/rodio#349] opened 2021-02-04 19:11 UTC
I use Rodio in my project to open and parse audio files to check if files are broken.
Due using cpal, my app crashes on OS which doesn't have installed audio packages and shows error 
```
error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
```
I don't need to play audio files, so it would be great to be able to disable cpal playback

**Comment by est31** [comment] 2021-02-04 19:14
That's an interesting idea. PRs welcome to add an optional "playback" feature

**Comment by omerdn1** [comment] 2024-12-21 22:05
@qarmin Is there any way to disable playback features in rodio? I saw the #[cfg(feature = "broken_audio")] but it doesn't seem to work

**Comment by dvdsk** [comment] 2024-12-21 22:10
@omerdn1 not currently, could you tell us a little about your use-case (why you want that). If it makes sense we may add it. We did recently get the functionality to output to a wav file, so using rodio without playback is not that far fetched anymore.

**Comment by omerdn1** [comment] 2024-12-21 22:12
@dvdsk We're using rodio in a Vercel Edge Function. These functions are very limited and you can't install dependencies outside of your app environment. Their cloud machines don't have alsa/libasound.so.2, so we're unable to use rodio unless we provide a binary file.

**Comment by qarmin** [comment] 2024-12-22 07:25
I tried to make a patch with the ability to disable cpal, but it was pretty much tied to other elements, so I didn't manage to do it.

Currently, to check if the file is broken I use Symphonia - https://github.com/qarmin/audio_checker/blob/master/src/lib.rs (symphonia panics sometimes with some really broken music files, so I suggest to use in project `panic = unwind` and `panic::catch_unwind` when executing this function to handle all panics)

**Comment by dvdsk** [comment] 2024-12-22 10:40
@PetrGlad whats your opinion on this?

**Comment by PetrGlad** [comment] 2024-12-22 16:08
Well, broken audio is normally fixed by offering patches that fix the problem... 
At the moment CPAL is a necessary part of rodio, since rodio was intended as a playback library, it is possible to adapt it also for audio processing without playback (as some sort of lighter implementation of DASP), but that would require substantial work. As I understand the problem is not disabling playback per se but gracefully degrading when playback cannot be started.

I see these cases here:
:one:  alsa is not available, and playback is not required - this may happen on server / in a data-center. Here ideally audio playback should be hidden behind a feature flag. If it is known in advance that there is no audio output, the `rodio` usage should be hidden behind a feature flag.
:two:  There are no suitable output devices or there is no ALSA. If output devices are missing user code may explicitly handle output stream opening errors. If it is known in advance that that there is no audio then just do not open the stream. A CPAL host implementation must be there, though.  On Linux one can install libasound to the target system just to fix linking, it should not do anything (except taking space), and skip opening the output stream or skip that initialization altogether. If it is not known in advance whether ALSA will be there, I am not sure how to handle it gracefully. The shared library is opened by linker so we have no control over it, unless we use `dlopen` explicitly and then do all the linking to CPAL ourselves somehow.
3. Playback is not required at all and rodio is used for some audio processing. In this case rodio needs a feature flag that excludes cpal dependency. This may need substantial work, since rodio uses some types from CPAL even if no output devices are used. If we can modify CPAL, we coul use "/dev/null" host implementation which looks to be already there but there is no clear way to force it. See the next, comment.... 

Regarding [[qarmin/czkawka]](https://github.com/qarmin/czkawka) I was going to suggest using `symphonia`  directly since they do not need playback and only check the files integrity. But looking at the sources, I can tell they already did this change. rodio is not in dependency tree anywhere (anymore?), they use [[qarmin/audio_checker]](https://github.com/qarmin/audio_checker) which uses `symphonia` directly.

@omerdn1 Regarding use in edge computing environment (in  those Vercel Edge Function). Edge functions do not normally interact with host devices, just do some dispatch or data processing. I would like to understand why rodio is there: is it used for audio processing but without playback, or is it an indirect external dependency that you cannot control/change?

**Comment by PetrGlad** [comment] 2024-12-22 16:19
It looks like cpal already have "null" host implementation that is used on unsupported platforms. See https://github.com/RustAudio/cpal/blob/582e93c41d6073df5d5da871989c5fd581ea04b8/src/platform/mod.rs#L729

Maybe CPAL may have an additional feature flag that forces that no-output implementation. So CPAL itself has to patched to make this possible. I think that just an additional target section in Cargo.toml would do.

**Comment by omerdn1** [comment] 2024-12-22 16:31
@PetrGlad We have a system that allows users to upload audio files. We then, based on some pre-conditions, perform audio processing and analysis on those files using rodio's Decoder (we extract sample data and have it go through analysis).

So as you might imagine, we fall under number 3.
Please don't hesitate to provide further direction as to what areas need to be looked at and/or tackled. Would love to contribute to this.

**Comment by PetrGlad** [comment] 2024-12-23 18:55
Regarding cpal modifications, it is not obvious how to add, say, optional "alsa" or "null-output"  feature so it does not interfere existing users. It is actually doable, see a patched version of cpal [[here]](https://github.com/RustAudio/cpal/compare/master...PetrGlad:cpal:optional-alsa) , if "alsa" feature is not enabled on this branch it will use null host on unix-like systems. I am not an expert in Cargo so maybe there is a better way to do the same. If you are in hurry, probably this could be an option to use this (or similarly patched) version of cpal.

I now think that it is possible to make cpal an optional feature of rodio, but this requires some work. Namely, almost all the uses of cpal are in `rodio::stream` which can be included conditionally, uses outside of that module are these type references 
* `cpal::SampleRate`
* `cpal::ChannelCount`
* `cpal::{FromSample, Sample as CpalSample}`

First two rodio can define itself if there is no cpal, and sample conversions are actually re-exported by cpal from `dasp-sample`  crate so maybe that can be used directly.

**Comment by dvdsk** [comment] 2024-12-23 20:20
> First two rodio can define itself if there is no cpal, and sample conversions are actually re-exported by cpal from `dasp-sample` crate so maybe that can be used directly.

I would consider just defining them in rodio and using them for everything. That way there is no need for conditional compilation. 

> Namely, almost all the uses of cpal are in rodio::stream

We could make `rodio::stream` optional it won't work without cpal anyway.

Cargo needs features to be additive so we can not have a feature that turns off playback. We can have one that enables it and put that in the default features list. A lot of rodio users use `default-features = false` however. There build will break when we do this, that is okay as long as we have clear warnings in docs. First time users should not have a problem since they should not have `default-features = false`.

Maybe we add two features:
 - playback, on by default enables `cpal` and `rodio::Stream`.
 - no-playback, removes compile errors that the playback feature is off.

Somewhere in rodio we then have the following code:
```rust
#[cfg(all(not(feature = "playback"), (feature = "no-playback"))]
compiler_error!("You have the playback feature disabled and you have not explicitly opted into using rodio without playback. If you want to use rodio without the ability to play sounds add the 'no-playback' feature. If this was a mistake and you need audio playback, please add the 'playback' feature or enabled the default-features for rodio").
```

Its against the rule that features should be additive but it might be okay, since there is no real functionality removed by enabling `no-playback`. What you think?

**Comment by PetrGlad** [comment] 2024-12-24 14:58
We can declare cpal as one of [default features](https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature), 
```toml
[features]
default = ["cpal"]
```
users that do not want playback support can refer to rodio as 
```toml
[dependencies]
rodio = { version="0.20.1",  default-features = false}
```
Disabling default features is a bit cumbersome but this seems to be an infrequent case, so most users will not be affected.

**Comment by PetrGlad** [comment] 2024-12-25 20:21
#349

**Closed** 2024-12-31 10:48 UTC

**Comment by dvdsk** [comment] 2024-12-31 10:56
@omerdn1 thanks to Petr's hard work we've got this implemented now. We will probably not release a new rodio version for a while (trying to get all the breaking changes like this in one big release). I recommend you use rodio as a git dependency and pin to a specific commit in `Cargo.toml`

**Comment by omerdn1** [comment] 2024-12-31 16:33
Love it guys! Thank you so much for the big efforts @PetrGlad @dvdsk
