### ISSUE TITLE
The spatial example is broken

### ISSUE THREAD

**Issue by teknico** [RustAudio/rodio#197] opened 2018-11-01 18:16 UTC
As of commit `a55cac7` the `spatial` example does not emit any sound. It was broken by part of #191.

**Comment by Xaeroxe** [comment] 2019-01-11 15:57
Can you please provide more info on your platform? I can't reproduce this on Windows 10 64 bit with the MSVC toolchain.

**Comment by teknico** [comment] 2019-01-11 20:12
I'm using Ubuntu 18.04. The fix is already merged (see above), to reproduce you have to revert it locally.

**Comment by Xaeroxe** [comment] 2019-01-11 20:19
Ah okay thanks

**Comment by est31** [comment] 2019-08-09 19:11
Seems fixed by 198

**Closed by est31** 2019-08-09 19:11 UTC
