### ISSUE TITLE
Does not build on iOS

### ISSUE THREAD

**Issue by johnnyw** [RustAudio/rodio#307] opened 2020-07-31 00:24 UTC
Attempting to build a rodio-dependent static library for iOS using lipo yields the following error:

```
error: failed to run custom build command for `coreaudio-sys v0.2.5`

Caused by:
  process didn't exit successfully: `/Users/johnwatson/Projects/rodio-demo/target/release/build/coreaudio-sys-ff45525eed014540/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
cargo:rustc-link-lib=framework=AudioUnit
cargo:rustc-link-lib=framework=CoreAudio
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
```

It looks like there may be a similar/related open issue in the repo for coreaudio-sys? https://github.com/RustAudio/coreaudio-sys/issues/29

**Comment by est31** [comment] 2020-07-31 01:24
I'd say this is a dupe of the bug you linked. Also, it's a build failure in the coreaudio-sys crate so it's better to report it there. Thanks!

**Closed by est31** 2020-07-31 01:24 UTC
